theme: jekyll-theme-tactile
title: GtkHash
description: A desktop utility for computing message digests or checksums
include: [".well-known"]
show_downloads: true
github:
  public: true
  owner_url: https://github.com/gtkhash/gtkhash
  zip_url: https://github.com/gtkhash/gtkhash/releases/latest
  tar_url: https://github.com/gtkhash/gtkhash/releases/latest
